### ISSUE TITLE
standoff size

### ISSUE THREAD

**Issue by stuart-warren** [soundmonster/samoklava#20]
Hello, I really like this project.

Sorry if this is a stupid question, I'm curious if you could provide the size of standoffs and screws that you use when building the full case

My guess is: 
* 3 layers of 1.6mm, perhaps you use different?
* thickness of hotswap sockets ~1.85mm

= 6.65mm

Do I need the standoffs to go through the 3 layers, or do the screw threads go through the outer layers?

Perhaps this could be added to the README

Thanks

**Comment by roubaobaozi** [comment]
The standoffs only go through the PCB, that's why the hole is larger in diameter than the screwholes for the top and bottom plates.

- Screw
- Top plate
- PCB
- Bottom plate
- Screw

The standoff height will be between the bottom face of the top plate, and the top face of the bottom plate.

HTH

**Comment by stuart-warren** [comment]
Cool thanks, so: 
The screws need to be long enough to go through the plate, plus a little bit and the standoffs need to be a similar size to the pcb and any components attached (excluding switches) ?

**Comment by roubaobaozi** [comment]
That's right, usually you'd be looking for M2 screws 3mm long (if using 1.6mm FR4 for top & bottom plates, obviously if you decide to get 3mm laser cut acrylic you need longer screws)

And you'd be after around about an M2 standoff at 8mm tall if FR4 top & bottom plates, and MX. I dunno what height if you're going choc though, sorry.

**Comment by soundmonster** [comment]
I'm using M2 x 5mm standoffs and the cheapest black M2 x ~3mm flathead screws I could find. These are obnoxiously expensive as they're marketed as "gaming SSD screws"; you're better off getting a bag from Ali Express. I've tried M2 x 4mm standoffs and they were too short for Kailh hotswap sockets for Chocs. Might work with soldered switches, though - haven't tried.

One other gotcha: there's one spot on the top plate where a flathead screw doesn't fit; I use a "regular" stainless steel round head screw there. They usually come with those mixed brass standoff packs anyway.
