### ISSUE TITLE
Error: Unexpected key "include_keys" within field "pcbs.top_plate"!

### ISSUE THREAD

**Issue by thoni56** [soundmonster/samoklava#22]
I ran the `build.sh` script locally (with `ergogen` locally). Unfortunately it failed too (#22) with

```
> ergogen samoklava.yaml

Ergogen v3.1.2 CLI

Interpreting format: YAML
Preprocessing input...
Calculating variables...
Parsing points...
Generating outlines...
Extruding cases...
Scaffolding PCBs...
Error: Unexpected key "include_keys" within field "pcbs.top_plate"!
    at exports.assert (C:\Users\Thomas\AppData\Roaming\npm\node_modules\ergogen\src\as
sert.js:12:15)
    at Object.exports.unexpected (C:\Users\Thomas\AppData\Roaming\npm\node_modules\erg
ogen\src\assert.js:35:9)
    at Object.exports.parse (C:\Users\Thomas\AppData\Roaming\npm\node_modules\ergogen\
src\pcbs.js:243:11)
    at Object.process (C:\Users\Thomas\AppData\Roaming\npm\node_modules\ergogen\src\er
gogen.js:84:27)
    at C:\Users\Thomas\AppData\Roaming\npm\node_modules\ergogen\src\cli.js:58:29
    at Object.<anonymous> (C:\Users\Thomas\AppData\Roaming\npm\node_modules\ergogen\sr
c\cli.js:126:3)
```

This is also evident when pasting the yaml into webversion of `ergogen`.

Perhaps this is what's causing #21 but we're not seeing the ergogen error. The build script finished with the same XIO error...

**Comment by thoni56** [comment]
This is with `ergogen` 3.1.2, but I don't get this error with 3.1.0 which is in the repos `package.json`, so it is probably not causing #21.

**Comment by soundmonster** [comment]
How did you install Ergogen? I would recommend using Samoklava's `Makefile`:

* `make setup` will install my Ergogen fork
* `make clean all` will generate and autoroute the board; requires Docker or Podman

**Comment by thoni56** [comment]
Thanks, yes, I learned that Samoklava has patched Ergogen. Not sufficiently visible there I would say. Thanks for reminding me to close this.
